/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLog {
  action: string;
  actor_id: string | null;
  category: Generated<string | null>;
  created_at: Generated<Timestamp | null>;
  data_after: Json | null;
  data_before: Json | null;
  duration_ms: number | null;
  error_message: string | null;
  id: Generated<Int8>;
  ip_address: string | null;
  metadata: Json | null;
  resource_id: string | null;
  resource_type: string | null;
  session_id: string | null;
  severity: Generated<string | null>;
  success: Generated<boolean | null>;
  user_agent: string | null;
}

export interface BroadcastDeliveries {
  broadcast_msg_id: string;
  conversation_id: string | null;
  delivered_at: Timestamp | null;
  read_at: Timestamp | null;
  user_id: string;
}

export interface BroadcastLists {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean | null>;
  metadata: Generated<Json | null>;
  name: string;
  owner_id: string;
  updated_at: Generated<Timestamp | null>;
}

export interface BroadcastMessages {
  body: string | null;
  broadcast_list_id: string;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  metadata: Generated<Json | null>;
  object_id: string | null;
  scheduled_at: Timestamp | null;
  sender_id: string;
  sent_at: Timestamp | null;
  status: Generated<string | null>;
  total_delivered: Generated<number | null>;
  total_read: Generated<number | null>;
  total_recipients: Generated<number | null>;
  type: Generated<string | null>;
}

export interface BroadcastRecipients {
  added_at: Generated<Timestamp | null>;
  added_by: string | null;
  broadcast_list_id: string;
  user_id: string;
}

export interface CallParticipants {
  avg_latency_ms: number | null;
  avg_packet_loss: Numeric | null;
  call_id: string;
  can_share_screen: Generated<boolean | null>;
  can_speak: Generated<boolean | null>;
  can_video: Generated<boolean | null>;
  id: Generated<string>;
  invited_at: Generated<Timestamp | null>;
  is_muted_by_host: Generated<boolean | null>;
  joined_at: Timestamp | null;
  left_at: Timestamp | null;
  status: Generated<string | null>;
  user_id: string;
}

export interface CallRecordings {
  call_id: string;
  consented_by: string[] | null;
  created_at: Generated<Timestamp | null>;
  ended_at: Timestamp | null;
  id: Generated<string>;
  is_available: Generated<boolean | null>;
  object_id: string;
  started_at: Generated<Timestamp | null>;
  started_by: string | null;
}

export interface Calls {
  answered_at: Timestamp | null;
  conversation_id: string | null;
  created_at: Generated<Timestamp | null>;
  duration_seconds: number | null;
  end_reason: string | null;
  ended_at: Timestamp | null;
  id: Generated<string>;
  initiated_at: Generated<Timestamp | null>;
  initiated_by: string;
  is_encrypted: Generated<boolean | null>;
  metadata: Generated<Json | null>;
  quality_stats: Generated<Json | null>;
  room_id: string | null;
  server_host: string | null;
  status: Generated<string | null>;
  type: string;
}

export interface ChannelJoinRequests {
  conversation_id: string;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  message: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  status: Generated<string | null>;
  user_id: string;
}

export interface ChannelSettings {
  category: string | null;
  conversation_id: string;
  is_official: Generated<boolean | null>;
  join_mode: Generated<string | null>;
  member_count: Generated<number | null>;
  post_restriction: Generated<string | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface ConversationEvents {
  actor_id: string | null;
  conversation_id: string;
  created_at: Generated<Timestamp | null>;
  data: Generated<Json | null>;
  event_type: string;
  id: Generated<string>;
  target_user_id: string | null;
}

export interface ConversationMembers {
  conversation_id: string;
  custom_permissions: Generated<Json | null>;
  id: Generated<string>;
  invited_by: string | null;
  is_hidden: Generated<boolean | null>;
  is_muted: Generated<boolean | null>;
  is_pinned: Generated<boolean | null>;
  joined_at: Generated<Timestamp | null>;
  last_read_at: Timestamp | null;
  last_read_msg_id: string | null;
  left_at: Timestamp | null;
  muted_until: Timestamp | null;
  role: Generated<string | null>;
  user_id: string;
}

export interface Conversations {
  avatar_object_id: string | null;
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  is_archived: Generated<boolean | null>;
  is_discoverable: Generated<boolean | null>;
  is_read_only: Generated<boolean | null>;
  last_message_at: Timestamp | null;
  last_message_id: string | null;
  max_members: number | null;
  metadata: Generated<Json | null>;
  name: string | null;
  topic: string | null;
  type: string;
  updated_at: Generated<Timestamp | null>;
}

export interface Drafts {
  body: string | null;
  conversation_id: string;
  pending_attachments: Generated<Json | null>;
  reply_to_id: string | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string;
}

export interface Games {
  conversation_id: string;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  kind: string;
  message_id: string;
  player1_id: string;
  player2_id: string;
  result: string | null;
  state: Generated<Json>;
  status: Generated<string>;
  updated_at: Generated<Timestamp | null>;
  winner_id: string | null;
}

export interface MessageAttachments {
  caption: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  message_id: string;
  object_id: string;
  sort_order: Generated<number | null>;
}

export interface MessageEdits {
  body_before: string;
  edited_at: Generated<Timestamp | null>;
  edited_by: string;
  id: Generated<string>;
  message_id: string;
}

export interface MessageReactions {
  created_at: Generated<Timestamp | null>;
  emoji: string;
  message_id: string;
  user_id: string;
}

export interface MessageReceipts {
  delivered_at: Timestamp | null;
  message_id: string;
  read_at: Timestamp | null;
  user_id: string;
}

export interface Messages {
  body: string | null;
  body_format: Generated<string | null>;
  conversation_id: string;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  edited_at: Timestamp | null;
  forwarded_from_conv: string | null;
  forwarded_from_id: string | null;
  id: Generated<string>;
  is_deleted: Generated<boolean | null>;
  is_edited: Generated<boolean | null>;
  link_preview: Json | null;
  metadata: Generated<Json | null>;
  reply_to_id: string | null;
  sender_id: string | null;
  sent_at: Generated<Timestamp | null>;
  system_data: Json | null;
  thread_id: string | null;
  type: Generated<string | null>;
}

export interface MessageSearchTokens {
  message_id: string;
  token: string;
}

export interface MonitoringSnapshots {
  cpu_proceso_pct: Numeric | null;
  error_rate_pct: Numeric | null;
  fecha_registro: Generated<Timestamp>;
  heap_pct: number | null;
  host: string;
  id: Generated<Int8>;
  latencia_db_ms: Numeric | null;
  mem_sistema_pct: number | null;
  pool_max: number | null;
  pool_ocupadas: number | null;
  proceso_inicio: Timestamp;
  qps: Numeric | null;
  requests_por_min: number | null;
}

export interface NotificationPreferences {
  email_enabled: Generated<boolean | null>;
  event_type: string;
  in_app_enabled: Generated<boolean | null>;
  push_enabled: Generated<boolean | null>;
  quiet_days: number[] | null;
  quiet_hours_end: string | null;
  quiet_hours_start: string | null;
  user_id: string;
}

export interface Notifications {
  body: string | null;
  channel: Generated<string | null>;
  created_at: Generated<Timestamp | null>;
  delivered_at: Timestamp | null;
  id: Generated<string>;
  is_read: Generated<boolean | null>;
  read_at: Timestamp | null;
  recipient_id: string;
  reference_data: Generated<Json | null>;
  reference_id: string | null;
  reference_type: string | null;
  title: string | null;
  type: string;
}

export interface Permissions {
  category: string;
  code: string;
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<string>;
}

export interface PinnedMessages {
  conversation_id: string;
  message_id: string;
  pinned_at: Generated<Timestamp | null>;
  pinned_by: string;
}

export interface PollOptions {
  id: Generated<string>;
  poll_id: string;
  sort_order: Generated<number | null>;
  text: string;
  vote_count: Generated<number | null>;
}

export interface Polls {
  closes_at: Timestamp | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  is_anonymous: Generated<boolean | null>;
  is_closed: Generated<boolean | null>;
  is_multiple: Generated<boolean | null>;
  message_id: string;
  question: string;
}

export interface PollVotes {
  option_id: string;
  poll_id: string;
  user_id: string;
  voted_at: Generated<Timestamp | null>;
}

export interface RolePermissions {
  permission_id: string;
  role_id: string;
}

export interface Roles {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  display_name: string;
  id: Generated<string>;
  is_system: Generated<boolean | null>;
  name: string;
  priority: Generated<number | null>;
}

export interface SavedMessages {
  message_id: string;
  note: string | null;
  saved_at: Generated<Timestamp | null>;
  user_id: string;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  name: string;
}

export interface StickerPacks {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  owner_id: string;
  position: Generated<number>;
}

export interface StickerUsage {
  last_used_at: Generated<Timestamp>;
  owner_id: string;
  storage_object_id: string;
  use_count: Generated<number>;
}

export interface StorageObjects {
  /**
   * private = solo accesible via presigned URL (recomendado para media de usuarios). public = accesible directo por URL (solo para assets públicos como stickers).
   */
  access_policy: Generated<string | null>;
  bucket_name: string;
  duration_ms: number | null;
  etag: string | null;
  exif_stripped: Generated<boolean | null>;
  expires_at: Timestamp | null;
  extra_metadata: Generated<Json | null>;
  /**
   * Hash SHA-256 del archivo. Antes de subir a MinIO el backend consulta si ya existe este hash. Si existe, reutiliza el mismo objeto (deduplicación) sin re-subir.
   */
  file_hash_sha256: string | null;
  file_size_bytes: Int8;
  id: Generated<string>;
  image_height: number | null;
  image_width: number | null;
  mime_type: string;
  /**
   * Ruta del objeto dentro del bucket. Convención: {tipo}/{año}/{mes}/{uuid}.{ext} Ej: images/2026/04/f47ac10b-58cc-4372-a567-0e02b2c3d479.jpg El prefijo permite lifecycle policies y cleanup por fecha en MinIO.
   */
  object_key: string;
  object_type: string;
  original_filename: string;
  page_count: number | null;
  processed_at: Timestamp | null;
  processing_error: string | null;
  processing_status: Generated<string | null>;
  thumbnail_bucket: Generated<string | null>;
  thumbnail_key: string | null;
  uploaded_at: Generated<Timestamp | null>;
  uploader_id: string | null;
  virus_scan_status: Generated<string | null>;
  virus_scanned_at: Timestamp | null;
}

export interface StoragePresignedUrls {
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: Generated<string>;
  object_id: string;
  operation: Generated<string | null>;
  presigned_url: string;
  user_id: string | null;
}

export interface SystemSettings {
  category: string | null;
  description: string | null;
  key: string;
  updated_at: Generated<Timestamp | null>;
  updated_by: string | null;
  value: Json;
}

export interface UserCredentials {
  created_at: Generated<Timestamp | null>;
  failed_attempts: Generated<number | null>;
  locked_until: Timestamp | null;
  must_change_pw: Generated<boolean | null>;
  password_hash: string;
  pw_changed_at: Generated<Timestamp | null>;
  updated_at: Generated<Timestamp | null>;
  user_id: string;
}

export interface UserRelationships {
  alias: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  target_user_id: string;
  type: string;
  user_id: string;
}

export interface UserRoles {
  expires_at: Timestamp | null;
  granted_at: Generated<Timestamp | null>;
  granted_by: string | null;
  role_id: string;
  user_id: string;
}

export interface Users {
  auth_provider: Generated<string>;
  avatar_bucket: Generated<string | null>;
  avatar_object_key: string | null;
  created_at: Generated<Timestamp | null>;
  department: string | null;
  display_name: string;
  email: string | null;
  external_id: string | null;
  id: Generated<string>;
  job_title: string | null;
  last_seen_at: Timestamp | null;
  locale: Generated<string | null>;
  metadata: Generated<Json | null>;
  phone_extension: string | null;
  presence: Generated<string | null>;
  presence_message: string | null;
  status: Generated<string | null>;
  timezone: Generated<string | null>;
  updated_at: Generated<Timestamp | null>;
  username: string;
}

export interface UserSessions {
  created_at: Generated<Timestamp | null>;
  device_name: string | null;
  device_type: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_address: string | null;
  is_active: Generated<boolean | null>;
  last_activity: Generated<Timestamp | null>;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface UserStickers {
  added_at: Generated<Timestamp>;
  id: Generated<string>;
  is_favorite: Generated<boolean>;
  keywords: Generated<string[]>;
  name: string | null;
  owner_id: string;
  pack_id: string | null;
  position: Generated<number>;
  storage_object_id: string;
}

export interface UserWallpapers {
  created_at: Generated<Timestamp | null>;
  scope: string;
  scope_key: string;
  storage_object_id: string | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string;
  wallpaper_type: string;
  wallpaper_value: string | null;
}

export interface DB {
  audit_log: AuditLog;
  broadcast_deliveries: BroadcastDeliveries;
  broadcast_lists: BroadcastLists;
  broadcast_messages: BroadcastMessages;
  broadcast_recipients: BroadcastRecipients;
  call_participants: CallParticipants;
  call_recordings: CallRecordings;
  calls: Calls;
  channel_join_requests: ChannelJoinRequests;
  channel_settings: ChannelSettings;
  conversation_events: ConversationEvents;
  conversation_members: ConversationMembers;
  conversations: Conversations;
  drafts: Drafts;
  games: Games;
  message_attachments: MessageAttachments;
  message_edits: MessageEdits;
  message_reactions: MessageReactions;
  message_receipts: MessageReceipts;
  message_search_tokens: MessageSearchTokens;
  messages: Messages;
  monitoring_snapshots: MonitoringSnapshots;
  notification_preferences: NotificationPreferences;
  notifications: Notifications;
  permissions: Permissions;
  pinned_messages: PinnedMessages;
  poll_options: PollOptions;
  poll_votes: PollVotes;
  polls: Polls;
  role_permissions: RolePermissions;
  roles: Roles;
  saved_messages: SavedMessages;
  schema_migrations: SchemaMigrations;
  sticker_packs: StickerPacks;
  sticker_usage: StickerUsage;
  storage_objects: StorageObjects;
  storage_presigned_urls: StoragePresignedUrls;
  system_settings: SystemSettings;
  user_credentials: UserCredentials;
  user_relationships: UserRelationships;
  user_roles: UserRoles;
  user_sessions: UserSessions;
  user_stickers: UserStickers;
  user_wallpapers: UserWallpapers;
  users: Users;
}
