module.exports = {
  authService: require('./auth.service'),
  userService: require('./user.service'),
  conversationService: require('./conversation.service'),
  channelService: require('./channel.service'),
  messageService: require('./message.service'),
  pollService: require('./poll.service'),
  callService: require('./call.service'),
  storageService: require('./storage.service'),
  broadcastService: require('./broadcast.service'),
  notificationService: require('./notification.service'),
  relationshipService: require('./relationship.service'),
  adminService: require('./admin.service'),
  wallpaperService: require('./wallpaper.service'),
  ldapService: require('./ldap.service'),
};
