module.exports = {
  userRepository: require('./user.repository'),
  credentialRepository: require('./credential.repository'),
  sessionRepository: require('./session.repository'),
  conversationRepository: require('./conversation.repository'),
  channelRepository: require('./channel.repository'),
  messageRepository: require('./message.repository'),
  savedMessageRepository: require('./saved.repository'),
  draftRepository: require('./draft.repository'),
  pollRepository: require('./poll.repository'),
  callRepository: require('./call.repository'),
  storageRepository: require('./storage.repository'),
  broadcastRepository: require('./broadcast.repository'),
  notificationRepository: require('./notification.repository'),
  auditRepository: require('./audit.repository'),
  relationshipRepository: require('./relationship.repository'),
  systemSettingsRepository: require('./systemSettings.repository'),
};
