module.exports = {
  authController: require('./auth.controller'),
  userController: require('./user.controller'),
  conversationController: require('./conversation.controller'),
  channelController: require('./channel.controller'),
  messageController: require('./message.controller'),
  pollController: require('./poll.controller'),
  gameController: require('./game.controller'),
  callController: require('./call.controller'),
  storageController: require('./storage.controller'),
  broadcastController: require('./broadcast.controller'),
  notificationController: require('./notification.controller'),
  relationshipController: require('./relationship.controller'),
  adminController: require('./admin.controller'),
  wallpaperController: require('./wallpaper.controller'),
};
